/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.threeglav.sh.bauk.rpc;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ProcessingResult implements org.apache.thrift.TEnum {
  SUCCESS(1),
  INVALID_FEED(2),
  PROCESSING_ERROR(3),
  UNKNOWN(4);

  private final int value;

  private ProcessingResult(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ProcessingResult findByValue(int value) { 
    switch (value) {
      case 1:
        return SUCCESS;
      case 2:
        return INVALID_FEED;
      case 3:
        return PROCESSING_ERROR;
      case 4:
        return UNKNOWN;
      default:
        return null;
    }
  }
}
